// <auto-generated />
using System;
using System.Collections.Generic;
using Fb4.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fb4.Backend.Migrations
{
    [DbContext(typeof(Fb4DbContext))]
    partial class Fb4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fb4.Backend.Domain.LaufwegEintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Gewicht")
                        .HasColumnType("numeric");

                    b.Property<string>("NachRoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VonRoomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Laufwege");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.LinkEintrag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gruppe")
                        .HasColumnType("text");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.MensaEintrag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Oeffnungszeiten")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("QuelleId")
                        .HasColumnType("text");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("integer");

                    b.Property<string>("SpeiseplanUrl")
                        .HasColumnType("text");

                    b.Property<bool>("StandardAuswahl")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Mensen");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.RaumEintrag", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<bool>("EkeyZugaenglich")
                        .HasColumnType("boolean");

                    b.Property<string>("Groesse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schliesszeit")
                        .HasColumnType("text");

                    b.HasKey("RoomId");

                    b.ToTable("Raeume");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.SammlungsRevision", b =>
                {
                    b.Property<string>("Bereich")
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Bereich");

                    b.ToTable("Revisionen");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.SemesterKalender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("NaechsterSommerSemesterBeginn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NaechsterWinterSemesterBeginn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SemesterBeginn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SemesterEnde")
                        .HasColumnType("date");

                    b.Property<int>("TicketLinks")
                        .HasColumnType("integer");

                    b.Property<int>("TicketOben")
                        .HasColumnType("integer");

                    b.Property<int>("TicketRechts")
                        .HasColumnType("integer");

                    b.Property<int>("TicketUnten")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SemesterKalender");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.StudiengangRueckfall", b =>
                {
                    b.Property<string>("Kurzname")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("Fachsemester")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Kurzname");

                    b.ToTable("StudiengangRueckfall");
                });

            modelBuilder.Entity("Fb4.Backend.Domain.Verwaltungsprotokoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DatensatzReferenz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Handlung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KontoAnzeigename")
                        .HasColumnType("text");

                    b.Property<string>("KontoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ZeitpunktUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ZeitpunktUtc");

                    b.ToTable("Verwaltungsprotokolle");
                });
#pragma warning restore 612, 618
        }
    }
}
